### ISSUE TITLE
API to recover password/pass phrase

### ISSUE THREAD

**Issue by DmitryEfimenko** [openpassphrase/opp#15]
If this app will be used by more people, it's just a matter of time till someone forgets their credentials.
For example, I'm one of these people.

There should be a mechanism to recover credentials. Usually, such mechanism involves sending an email with a link that will allow a user to reset a password.

At this time we do not store people's email addresses. We could require username to be an email address.

**Comment by abashmak** [comment]
The email as username is definitely a non-starter. I know people who would absolutely hate that. I am one of those people. We could ask for an email optionally during registration specifically for the purposes of recovering the username and resetting the password. In order to do that we'd have to build a verification mechanism that triggers an email during registration. That's probably out of the scope of this project at the moment.

P.S. The password cannot be recovered since it's only stored in a hashed form, it can only be reset. The encryption phrase is not even stored anywhere on the server, and furthermore, it is also not possible to reset it, since we'd be unable to decrypt any of the existing data. It is designed to permanently live only in the brain of the user, so you best never forget the passphrase!!!

**Comment by DmitryEfimenko** [comment]
right. I forgot that about the phrase... We should probably keep this in mind when building UI for that and put a big warning when setting the phrase

**Comment by DmitryEfimenko** [comment]
coming back to this...
I'm thinking we could actually reset a pass phrase. Although it'd take a bit different form.
* On the "Reset Pass Phrase" screen we ask for the old Phrase and the new Phrase
* Use old phrase to decrypt all passwords
* Use new phrase to encrypt all passwords and save them again.

Thoughts?

**Comment by abashmak** [comment]
If you have to know the old passphrase, then it's not resetting, it's changing! So yes, we could have a "Change Passphrase" page on the UI. There's already a CLI tool to decrypt/re-encrypt, so can easily be made into an API route. Feel free to open a different issue for this.
